name: run test hello-devops

on:
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - 'release/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, 'Merge branch main into')"  # Prevent running if the push is from main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Test Command
        run: |
          echo "Hello Devops1"